Added facebook page & fixed dev pics
bricesuazo/cvsu.me pull request #92
Opened 2024-09-05 11:00 UTC by tfudoinkebs

Added Facebook page using Aceternity UI & updated dev pics

2024-09-05 12:08 UTC, bricesuazo requested changes
- Notify Rey about the text contents in features section
- Add NGL for platform. After the Partnerships section
- Follow the text format for title and subtitle in `Follow us on Facebook` section
- Add shadow transition in facebook page card
- Make the contact us form center. Make the `Email` and `Facebook` icon.

2024-09-06 07:48 UTC, aaronjoshuaespinosa reviewed
nice!

2024-09-08 08:31 UTC, bricesuazo approved these changes

2024-09-08 08:31 UTC, bricesuazo commented on apps/www/src/components/ngl.tsx
> +          <Link href="https://github.com/" target="_blank">
Fix this link. It should be `env.NEXT_PUBLIC_NGL_URL/kabsu.me`

2024-09-08 08:36 UTC, merged